in-root:
- any: ['**/*', '!src/abstraction/**/*']

in-eq1Producteur1: 
- /src/abstraction/eq1Producteur1/**/*

in-eq2Producteur2:
- /src/abstraction/eq2Producteur2/**/*

in-eq3Producteur3:
- /src/abstraction/eq3Producteur3/**/*

in-eq4Transformateur1:
- /src/abstraction/eq4Transformateur1/**/*

in-eq5Transformateur2:
- /src/abstraction/eq5Transformateur2/**/*

in-eq6Transformateur3:
- /src/abstraction/eq6Transformateur3/**/*

in-eq7Distributeur1:
- /src/abstraction/eq7Distributeur1/**/*

in-eq8Distributeur2:
- /src/abstraction/eq8Distributeur2/**/*

in-eq9Distributeur3:
- /src/abstraction/eq9Distributeur3/**/*

in-eqXRomu:
- /src/abstraction/eqXRomu/**/*
