in-root:
- all: ['**/*', '!/src/abstraction/**/*']

in-eq1Producteur1: 
- all: ['/src/abstraction/eq1Producteur1/**/*']

in-eq2Producteur2:
- all: ['/src/abstraction/eq2Producteur2/**/*']

in-eq3Producteur3:
- all: ['/src/abstraction/eq3Producteur3/**/*']

in-eq4Transformateur1:
- all: ['/src/abstraction/eq4Transformateur1/**/*']

in-eq5Transformateur2:
- all: ['/src/abstraction/eq5Transformateur2/**/*']

in-eq6Transformateur3:
- all: ['/src/abstraction/eq6Transformateur3/**/*']

in-eq7Distributeur1:
- all: ['/src/abstraction/eq7Distributeur1/**/*']

in-eq8Distributeur2:
- all: ['/src/abstraction/eq8Distributeur2/**/*']

in-eq9Distributeur3:
- all: ['/src/abstraction/eq9Distributeur3/**/*']

in-eqXRomu:
- all: ['/src/abstraction/eqXRomu/**/*']
