by-eq1Producteur1: 
- '@Heatszy'
- '@Charles141002'
- '@elouanzer'
- '@gabvyl'

by-eq2Producteur2:
- '@Nyosema'
- '@EragonKing2020'
- '@Flodspl'
- '@Tobusss'

by-eq3Producteur3:
- '@Dahan13'
- '@marine-naveros'
- '@Ewwweee'
- '@VictorDCh'

by-eq4Transformateur1:
- '@AlexianBtrl'
- '@ProgRaizell'
- '@Aminee100'
- '@noobsensei92'

by-eq5Transformateur2:
- '@matdou'
- '@yassinge60'
- '@WIEMLABBAOUI'
- '@noikitu'

by-eq6Transformateur3:
- '@NathanSlbg'
- '@Momo1505'
- '@Mactuxy'
- '@nathan-claeys'

by-eq7Distributeur1:
- '@ghalys'
- '@laaro'
- '@theoo33'
- '@romano122333'

by-eq8Distributeur2:
- '@MariemMARZOUGUI'
- '@Kayus54'
- '@senku33'
- '@Maxime443'

by-eq9Distributeur3:
- '@BaptisteBAYLE'
- '@MathildeSOUN'
- '@Prisma34'
- '@XxWillyxX'

by-eqXRomu:
- '@romualdDebruyne'
