name: File ownership
on: pull_request_target

jobs:
  checkfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: tspascoal/get-user-teams-membership@v2
        id: actorTeams
        with:
          username: ${{ github.event.pull_request.user.login }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            eq1Producteur1:
              - 'src/abstraction/eq1Producteur1/**'
            eq2Producteur2:
              - 'src/abstraction/eq2Producteur2/**'
            eq3Producteur3:
              - 'src/abstraction/eq3Producteur3/**'
            eq4Transformateur1:
              - 'src/abstraction/eq4Transformateur1/**'
            eq5Transformateur2:
              - 'src/abstraction/eq5Transformateur2/**'
            eq6Transformateur3:
              - 'src/abstraction/eq6Transformateur3/**'
            eq7Distributeur1:
              - 'src/abstraction/eq7Distributeur1/**'
            eq8Distributeur2:
              - 'src/abstraction/eq8Distributeur2/**'
            eq9Distributeur3:
              - 'src/abstraction/eq9Distributeur3/**'
            eqXRomu:
              - 'src/abstraction/eqXRomu/**'
              - 'src/controle/**'
              - 'src/presentation/**'
            root:
              - '*'
              - '.github/**'
              - '.settings/**'
              - 'docs/**'
              - 'lib/**'
              - 'test/**'

      - name: Enable auto-merge
        if: fromJSON(steps.filter.outputs.changes)[1] == null && fromJSON(steps.filter.outputs.changes)[0] == steps.actorTeams.outputs.teams[0]
        run: |
          echo ${{ fromJSON(steps.filter.outputs.changes)[1] }}
          echo ${{ steps.filter.outputs.changes }}
          echo ${{ steps.actorTeams.outputs.teams }} 
          gh pr merge --auto --merge ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          
      - name: Exit
        if: fromJSON(steps.filter.outputs.changes)[1] != null || fromJSON(steps.filter.outputs.changes)[0] != steps.actorTeams.outputs.teams[0]
        run: exit 1
